version: '3'
services:
  zookeeper:
    image: sgkafka:2.8.0
    command: ./start.sh zookeeper
    ports:
      - "2181:2181"
        
  kafka-1:
    image: sgkafka:2.8.0
    command: ./start.sh kafka-broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka1.test.local
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 500
      KAFKA_offsets_topic_replication_factor: 3

  kafka-2:
    image: sgkafka:2.8.0
    command: ./start.sh kafka-broker
    ports:
      - "9093:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka2.test.local
      KAFKA_ADVERTISED_PORT: 9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 501
      KAFKA_offsets_topic_replication_factor: 3

  kafka-3:
    image: sgkafka:2.8.0
    command: ./start.sh kafka-broker
    ports:
      - "9094:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka1.test.local
      KAFKA_ADVERTISED_PORT: 9094
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 502
      KAFKA_offsets_topic_replication_factor: 3
